#!/bin/bash
yum install -y apr 
yum install -y apr-util-1.5.2-6.el7 
yum install -y autoconf
yum install -y automake
yum install -y bison
yum install -y cmake
yum install -y compat-db47-4.7.25-28.el7
yum install -y ctags
yum install -y elfutils-libelf-0.176-5.el7
yum install -y expect
yum install -y flex
yum install -y gcc
yum install -y gcc-c++ 
yum install -y gitk.noarch
yum install -y git.x86_64
yum install -y glibc
yum install -y glibc-devel
yum install -y glibc-devel.i686
yum install -y gvim 
yum install -y hdf5 fftw lapack*
yum install -y ipa-client 
yum install -y jq
yum install -y ksh
yum install -y libcgroup 
yum install -y libcgroup-tools 
yum install -y libibverbs
yum install -y libncurses.so.5 
yum install -y libQt5Designer.so.5
yum install -y libreoffice
yum install -y libSM 
yum install -y libstdc 
yum install -y libstdc++.so.5
yum install -y libtiff 
yum install -y libtool
yum install -y libudev*
yum install -y libXcursor 
yum install -y libXext.so.6 
yum install -y libxkbcommon
yum install -y libXmu.i686
yum install -y libXp
yum install -y libXrandr 
yum install -y libXrender.i686 
yum install -y libXScrnSaver-1.2.2-6.1.el7
yum install -y libXss.so.1
yum install -y libXt-devel-1.1.5-3.el7.x86_64
yum install -y libXt.i686 
yum install -y meld
yum install -y mesa-libGLU
yum install -y motif
yum install -y motif-devel-2.3.4-14.el7_5.x86_64
yum install -y ncurses-libs 
yum install -y net-tools
yum install -y nfs-utils 
yum install -y ntp 
yum install -y ntpdate
yum install -y ntp-doc 
yum install -y ntp-perl 
yum install -y numactl
yum install -y opensm 
yum install -y openssl-devel
yum install -y pkg-config
yum install -y pkgconfig 
yum install -y poppler-cpp-devel 
yum install -y pulseaudio-libs 
yum install -y python3-devel
yum install -y python-flake8
yum install -y redhat-lsb
yum install -y rpcbind 
yum install -y rsh
yum install -y subversion 
yum install -y telnet
yum install -y terminator
yum install -y tkdiff
yum install -y tmpwatch
yum install -y tree.x86_64
yum install -y unixODBC-devel.i686 
yum install -y unixODBC-devel.x86_64 
yum install -y unixODBC.i686
yum install -y unixODBC.x86_64 
yum install -y vim-X11.x86_64
yum install -y wx*
yum install -y xclip emacs ddd
yum install -y xorg-x11-fonts-misc
yum install -y xterm
yum install -y Xvfb
yum install -y zlib 
yum install -y zsh
